/**
 * The product lines the studio offers, and how each one's documented
 * endpoints fold into modes. Every `model` here must exist in
 * generated/catalog.json — the adapter throws at startup otherwise, so a
 * stale id never ships silently.
 */
import type { Family, ModeSpec } from "./auto";
import type { Values } from "./types";

const m = (id: string, label: string, model: string, extra: Partial<ModeSpec> = {}): ModeSpec => ({
  id,
  label,
  model,
  ...extra,
});

/**
 * Gemini Omni shares seven slots between its inputs: a picture takes one, a
 * video two, a character one.
 */
function omniBudget(v: Values): string | null {
  const count = (key: string) => (Array.isArray(v[key]) ? (v[key] as unknown[]).length : 0);
  const used = count("image_urls") + 2 * count("video_list") + count("character_ids");
  if (used <= 7) return null;
  return count("video_list") > 0
    ? `With a video, Gemini Omni takes up to ${Math.max(0, 5 - count("character_ids"))} images.`
    : "Gemini Omni takes up to 7 images and characters together.";
}

/** Seedance 2.x share one schema; the three input styles are exclusive. */
const seedanceModes = (model: string, refs = true): ModeSpec[] => [
  m("text-to-video", "Text to video", model, {
    hide: ["first_frame_url", "last_frame_url", "reference_image_urls", "reference_video_urls", "reference_audio_urls"],
    require: ["prompt"],
  }),
  m("image-to-video", "Image to video", model, {
    hint: "First frame, optionally a last frame",
    hide: ["reference_image_urls", "reference_video_urls", "reference_audio_urls"],
    require: ["first_frame_url"],
  }),
  ...(refs
    ? [
        m("reference-to-video", "Reference", model, {
          hint: "Images, videos and audio as references",
          hide: ["first_frame_url", "last_frame_url"],
        }),
      ]
    : []),
];

const RUNWAY_FIELDS: Family["fields"] = {
  quality: {
    kind: "segmented",
    placement: "bar",
    default: "720p",
    choices: [
      { value: "720p", label: "720p" },
      { value: "1080p", label: "1080p", hint: "Not with 10-second clips" },
    ],
  },
  duration: {
    kind: "segmented",
    placement: "bar",
    default: 5,
    choices: [
      { value: "5", label: "5s" },
      { value: "10", label: "10s", hint: "Not at 1080p" },
    ],
  },
};

const MOTION_CONTROL_FIELDS: Family["fields"] = {
  mode: {
    kind: "segmented",
    placement: "bar",
    choices: [
      { value: "std", label: "Standard", hint: "720p" },
      { value: "pro", label: "Pro", hint: "1080p" },
    ],
  },
  character_orientation: {
    kind: "segmented",
    placement: "bar",
    choices: [
      { value: "video", label: "Follow video" },
      { value: "image", label: "Follow image" },
    ],
  },
  background_source: {
    kind: "segmented",
    placement: "panel",
    choices: [
      { value: "input_video", label: "Video background" },
      { value: "input_image", label: "Image background" },
    ],
  },
};

export const FAMILIES: Family[] = [
  /* ============================================================== *
   * IMAGE
   * ============================================================== */
  {
    id: "nano-banana-2",
    featured: true,
    prompts: [
      "A product still of a matte ceramic mug on wet slate, soft window light, shallow depth of field",
      "Editorial portrait, 85mm, golden hour, film grain, muted teal and amber",
    ],
    name: "Nano Banana 2",
    vendor: "Google",
    category: "image",
    output: "image",
    badge: "4K",
    tagline: "Gemini 3.1 Flash Image: fast, sharp text rendering, up to 14 references.",
    modes: [
      m("generate", "Generate", "nano-banana-2", { hide: ["image_input"] }),
      m("edit", "Edit", "nano-banana-2", { hint: "Up to 14 reference images", require: ["image_input"] }),
    ],
  },
  {
    id: "nano-banana-2-lite",
    name: "Nano Banana 2 Lite",
    vendor: "Google",
    category: "image",
    output: "image",
    tagline: "The fastest, cheapest Nano Banana: 1K output, up to 10 references.",
    modes: [
      m("generate", "Generate", "nano-banana-2-lite", { hide: ["image_urls"] }),
      m("edit", "Edit", "nano-banana-2-lite", { require: ["image_urls"] }),
    ],
  },
  {
    id: "nano-banana-pro",
    name: "Nano Banana Pro",
    vendor: "Google",
    category: "image",
    output: "image",
    badge: "4K",
    tagline: "Pro-grade Nano Banana with up to 8 reference images and 4K output.",
    modes: [
      m("generate", "Generate", "nano-banana-pro", { hide: ["image_input"] }),
      m("edit", "Edit", "nano-banana-pro", { require: ["image_input"] }),
    ],
  },
  {
    id: "nano-banana",
    name: "Nano Banana",
    vendor: "Google",
    category: "image",
    output: "image",
    tagline: "The original Gemini image model: quick generation and editing.",
    modes: [
      m("generate", "Generate", "google/nano-banana"),
      m("edit", "Edit", "google/nano-banana-edit", { hint: "Up to 10 images" }),
    ],
  },
  {
    id: "imagen-4",
    name: "Imagen 4",
    vendor: "Google",
    category: "image",
    output: "image",
    tagline: "Google's photoreal image model at its standard tier.",
    modes: [m("generate", "Generate", "google/imagen4")],
  },
  {
    id: "imagen-4-fast",
    name: "Imagen 4 Fast",
    vendor: "Google",
    category: "image",
    output: "image",
    tagline: "The cheaper, quicker Imagen 4 tier.",
    modes: [m("generate", "Generate", "google/imagen4-fast")],
  },
  {
    id: "imagen-4-ultra",
    name: "Imagen 4 Ultra",
    vendor: "Google",
    category: "image",
    output: "image",
    tagline: "The highest-fidelity Imagen 4 tier.",
    modes: [m("generate", "Generate", "google/imagen4-ultra")],
  },
  {
    id: "seedream-5-pro",
    featured: true,
    prompts: [
      "Isometric cutaway of a tiny bookshop at night, warm lamps, rain on the glass",
      "Poster with bold bilingual typography: 'NIGHT MARKET' in neon over a wet street",
    ],
    name: "Seedream 5 Pro",
    vendor: "ByteDance",
    category: "image",
    output: "image",
    tagline: "Controlled generation, precision editing and layer decomposition.",
    modes: [
      m("generate", "Generate", "seedream/5-pro-text-to-image"),
      m("edit", "Edit", "seedream/5-pro-image-to-image", { hint: "Up to 10 references" }),
      m("layers", "Layer decomposition", "seedream/5-pro-layer-decomposition", {
        hint: "Split an image into editable layers",
      }),
    ],
  },
  {
    id: "seedream-5-lite",
    name: "Seedream 5 Lite",
    vendor: "ByteDance",
    category: "image",
    output: "image",
    tagline: "Fast Seedream with basic, high and ultra quality tiers.",
    modes: [
      m("generate", "Generate", "seedream/5-lite-text-to-image"),
      m("edit", "Edit", "seedream/5-lite-image-to-image", { hint: "Up to 14 references" }),
    ],
  },
  {
    id: "seedream-4-5",
    name: "Seedream 4.5",
    vendor: "ByteDance",
    category: "image",
    output: "image",
    tagline: "Photoreal generation and multi-reference editing.",
    modes: [
      m("generate", "Generate", "seedream/4.5-text-to-image"),
      m("edit", "Edit", "seedream/4.5-edit"),
    ],
  },
  {
    id: "seedream-4",
    name: "Seedream 4.0",
    vendor: "ByteDance",
    category: "image",
    output: "image",
    tagline: "Batch up to six images per run, up to 4K.",
    modes: [
      m("generate", "Generate", "bytedance/seedream-v4-text-to-image"),
      m("edit", "Edit", "bytedance/seedream-v4-edit"),
    ],
  },
  {
    id: "seedream-3",
    name: "Seedream 3.0",
    vendor: "ByteDance",
    category: "image",
    output: "image",
    tagline: "The classic Seedream text-to-image model.",
    modes: [m("generate", "Generate", "bytedance/seedream")],
  },
  {
    id: "gpt-image-2",
    featured: true,
    prompts: [
      "A hand-drawn infographic explaining how coffee is roasted, ink and watercolour",
      "Minimal app icon: a paper plane folded from a map, flat, two colours",
    ],
    name: "GPT Image 2",
    vendor: "OpenAI",
    category: "image",
    output: "image",
    tagline: "Instruction-following image model with up to 16 references and 4K output.",
    modes: [
      m("generate", "Generate", "gpt-image-2-text-to-image"),
      m("edit", "Edit", "gpt-image-2-image-to-image", { hint: "Up to 16 references" }),
    ],
  },
  {
    id: "gpt-image-2-5-flare",
    name: "GPT Image 2.5 Flare",
    vendor: "OpenAI",
    category: "image",
    output: "image",
    badge: "NEW",
    tagline: "GPT Image 2.5, Flare tuning: vivid, high-contrast renders.",
    modes: [
      m("generate", "Generate", "gpt-image-2-5-flare-text-to-image"),
      m("edit", "Edit", "gpt-image-2-5-flare-image-to-image"),
    ],
  },
  {
    id: "gpt-image-2-5-sunburst",
    name: "GPT Image 2.5 Sunburst",
    vendor: "OpenAI",
    category: "image",
    output: "image",
    badge: "NEW",
    tagline: "GPT Image 2.5, Sunburst tuning: warm, naturalistic light.",
    modes: [
      m("generate", "Generate", "gpt-image-2-5-sunburst-text-to-image"),
      m("edit", "Edit", "gpt-image-2-5-sunburst-image-to-image"),
    ],
  },
  {
    id: "gpt-image-1-5",
    name: "GPT Image 1.5",
    vendor: "OpenAI",
    category: "image",
    output: "image",
    tagline: "Previous-generation GPT Image with medium and high quality.",
    modes: [
      m("generate", "Generate", "gpt-image/1.5-text-to-image"),
      m("edit", "Edit", "gpt-image/1.5-image-to-image"),
    ],
  },
  {
    id: "4o-image",
    name: "4o Image",
    vendor: "OpenAI",
    category: "image",
    output: "image",
    tagline: "GPT-4o image generation with up to five reference images.",
    modes: [m("generate", "Generate", "4o-image-api", { hide: ["file_url"] })],
  },
  {
    id: "flux-2-pro",
    featured: true,
    prompts: [
      "Architectural photo of a concrete house in a pine forest, overcast, ultra-detailed",
      "Close-up of frost forming on a red maple leaf, macro, morning light",
    ],
    name: "FLUX 2 Pro",
    vendor: "Black Forest Labs",
    category: "image",
    output: "image",
    tagline: "Fast, reliable photoreal generation with 1–8 reference images.",
    modes: [
      m("generate", "Generate", "flux-2/pro-text-to-image"),
      m("reference", "Reference", "flux-2/pro-image-to-image", { hint: "1–8 reference images" }),
    ],
  },
  {
    id: "flux-2-flex",
    name: "FLUX 2 Flex",
    vendor: "Black Forest Labs",
    category: "image",
    output: "image",
    tagline: "FLUX 2 with more control and fine-tuning headroom.",
    modes: [
      m("generate", "Generate", "flux-2/flex-text-to-image"),
      m("reference", "Reference", "flux-2/flex-image-to-image", { hint: "1–8 reference images" }),
    ],
  },
  {
    id: "flux-kontext",
    name: "FLUX Kontext",
    vendor: "Black Forest Labs",
    category: "image",
    output: "image",
    tagline: "In-context editing that keeps the rest of the frame untouched.",
    modes: [
      m("generate", "Generate", "flux1-kontext", { hide: ["input_image"] }),
      m("edit", "Edit", "flux1-kontext", { require: ["input_image"] }),
    ],
  },
  {
    id: "grok-imagine-image-2",
    name: "Grok Imagine Image 2.0",
    vendor: "xAI",
    category: "image",
    output: "image",
    tagline: "xAI's image model with segment-based editing.",
    modes: [
      m("generate", "Generate", "grok-imagine-image-2-0/text-to-image"),
      m("edit", "Edit", "grok-imagine-image-2-0/image-edit", { hint: "1–5 references" }),
      m("segment-map-task", "Segment map", "grok-imagine-image-2-0/segment-map", {
        variant: "task_id",
        hint: "From a previous Grok task",
      }),
      m("segment-map-image", "Segment map (image)", "grok-imagine-image-2-0/segment-map", {
        variant: "image_url",
        hint: "From an uploaded image",
      }),
      m("segment-edit", "Segment edit", "grok-imagine-image-2-0/segment-edit", {
        hint: "Edit selected segments of a mapped image",
      }),
    ],
  },
  {
    id: "grok-imagine-image",
    name: "Grok Imagine",
    vendor: "xAI",
    category: "image",
    output: "image",
    tagline: "The first Grok Imagine image model.",
    modes: [
      m("generate", "Generate", "grok-imagine/text-to-image"),
      m("edit", "Image to image", "grok-imagine/image-to-image"),
    ],
  },
  {
    id: "ideogram-v3",
    name: "Ideogram V3",
    vendor: "Ideogram",
    category: "image",
    output: "image",
    tagline: "Typography-strong generation, masked editing and remixing.",
    modes: [
      m("generate", "Generate", "ideogram/v3-text-to-image"),
      m("edit", "Edit", "ideogram/v3-edit", { hint: "Masked inpainting" }),
      m("remix", "Remix", "ideogram/v3-remix"),
    ],
  },
  {
    id: "ideogram-character",
    name: "Ideogram Character",
    vendor: "Ideogram",
    category: "image",
    output: "image",
    tagline: "Consistent characters from reference images, with edit and remix.",
    modes: [
      m("generate", "Generate", "ideogram/character"),
      m("edit", "Edit", "ideogram/character-edit"),
      m("remix", "Remix", "ideogram/character-remix"),
    ],
  },
  {
    id: "qwen-image",
    name: "Qwen Image",
    vendor: "Alibaba",
    category: "image",
    output: "image",
    tagline: "Open-weights generation and editing with full sampler control.",
    modes: [
      m("generate", "Generate", "qwen/text-to-image"),
      m("image-to-image", "Image to image", "qwen/image-to-image"),
      m("edit", "Edit", "qwen/image-edit"),
    ],
  },
  {
    id: "qwen2-image",
    name: "Qwen2 Image",
    vendor: "Alibaba",
    category: "image",
    output: "image",
    tagline: "Second-generation Qwen image editing.",
    modes: [m("edit", "Edit", "qwen2/image-edit")],
  },
  {
    id: "qwen3-image",
    name: "Qwen3 Image",
    vendor: "Alibaba",
    category: "image",
    output: "image",
    tagline: "Qwen3 image generation and editing, up to 2K.",
    modes: [
      m("generate", "Generate", "qwen3/text-to-image"),
      m("image-to-image", "Image to image", "qwen3/image-to-image"),
    ],
  },
  {
    id: "qwen3-image-pro",
    name: "Qwen3 Image Pro",
    vendor: "Alibaba",
    category: "image",
    output: "image",
    tagline: "The Pro tier of Qwen3 image generation and editing.",
    modes: [
      m("generate", "Generate", "qwen3/pro-text-to-image"),
      m("image-to-image", "Image to image", "qwen3/pro-image-to-image"),
    ],
  },
  {
    id: "qwen2-1-image",
    name: "Qwen 2.1 Image",
    vendor: "Alibaba",
    category: "image",
    output: "image",
    badge: "NEW",
    tagline: "Generation and masked editing with transparent backgrounds, up to 2K.",
    modes: [
      m("generate", "Generate", "qwen2-1/text-to-image"),
      m("image-to-image", "Image to image", "qwen2-1/image-to-image"),
    ],
  },
  {
    id: "wan-2-7-image",
    name: "Wan 2.7 Image",
    vendor: "Alibaba",
    category: "image",
    output: "image",
    tagline: "Sequential image sets, colour palettes and box-guided edits.",
    modes: [m("generate", "Generate", "wan/2-7-image")],
  },
  {
    id: "wan-2-7-image-pro",
    name: "Wan 2.7 Image Pro",
    vendor: "Alibaba",
    category: "image",
    output: "image",
    tagline: "The Pro tier of Wan 2.7 Image.",
    modes: [m("generate", "Generate", "wan/2-7-image-pro")],
  },
  {
    id: "z-image",
    name: "Z-Image",
    vendor: "Tongyi-MAI",
    category: "image",
    output: "image",
    tagline: "Bilingual model with reliable Chinese and English text rendering.",
    modes: [m("generate", "Generate", "z-image")],
  },

  /* ============================================================== *
   * VIDEO
   * ============================================================== */
  {
    id: "veo-3-1",
    featured: true,
    prompts: [
      "Slow dolly through a Tokyo alley at night, rain, neon reflections, ambient street sound",
      "A golden retriever shakes off water in slow motion on a beach at sunset",
    ],
    name: "Veo 3.1",
    vendor: "Google DeepMind",
    category: "video",
    output: "video",
    badge: "4K",
    tagline: "Cinematic motion with native audio: text, frames or material references.",
    modes: [
      m("text-to-video", "Text to video", "veo-3-1", {
        hide: ["image_urls"],
        fixed: { generation_type: "TEXT_2_VIDEO" },
      }),
      m("frames-to-video", "Frames to video", "veo-3-1", {
        hint: "One image, or first + last frame",
        require: ["image_urls"],
        fixed: { generation_type: "FIRST_AND_LAST_FRAMES_2_VIDEO" },
      }),
      m("reference-to-video", "Reference", "veo-3-1", {
        hint: "Material images · Fast/Lite models · 8s only",
        require: ["image_urls"],
        fixed: { generation_type: "REFERENCE_2_VIDEO" },
      }),
      m("extend", "Extend", "veo/extend", { hint: "Continue a finished Veo task" }),
      m("get-1080p", "Fetch 1080p", "veo/get-1080p-video", { hint: "Upgrade a finished task" }),
      m("get-4k", "Fetch 4K", "veo/get-4k-video", { hint: "Upgrade a finished task" }),
    ],
  },
  {
    id: "seedance-2-5",
    featured: true,
    prompts: [
      "Handheld tracking shot following a cyclist through a misty forest road at dawn",
      "A chef flips a pan of vegetables, sparks of flame, close-up, kitchen ambience",
    ],
    name: "Seedance 2.5",
    vendor: "ByteDance",
    category: "video",
    output: "video",
    badge: "AUDIO",
    tagline: "Multimodal references, first/last-frame control and native audio.",
    modes: seedanceModes("bytedance/seedance-2-5"),
  },
  {
    id: "seedance-2",
    name: "Seedance 2.0",
    vendor: "ByteDance",
    category: "video",
    output: "video",
    badge: "4K",
    tagline: "Seedance 2.0: up to 4K with references, frames and audio.",
    modes: seedanceModes("bytedance/seedance-2"),
  },
  {
    id: "seedance-2-fast",
    name: "Seedance 2.0 Fast",
    vendor: "ByteDance",
    category: "video",
    output: "video",
    tagline: "Quicker Seedance 2.0 at up to 720p.",
    modes: seedanceModes("bytedance/seedance-2-fast"),
  },
  {
    id: "seedance-2-mini",
    name: "Seedance 2.0 Mini",
    vendor: "ByteDance",
    category: "video",
    output: "video",
    tagline: "The lightest Seedance 2.0 for high-volume work.",
    modes: seedanceModes("bytedance/seedance-2-mini"),
  },
  {
    id: "seedance-1-5-pro",
    name: "Seedance 1.5 Pro",
    vendor: "ByteDance",
    category: "video",
    output: "video",
    tagline: "Seedance 1.5 with lens locking and optional audio.",
    modes: [
      m("text-to-video", "Text to video", "bytedance/seedance-1.5-pro", { hide: ["input_urls"] }),
      m("image-to-video", "Image to video", "bytedance/seedance-1.5-pro", {
        hint: "One or two frames",
        require: ["input_urls"],
      }),
    ],
  },
  {
    id: "seedance-1-pro",
    name: "Seedance 1.0 Pro",
    vendor: "ByteDance",
    category: "video",
    output: "video",
    tagline: "The Pro tier of Seedance 1.0, in text and image modes.",
    modes: [
      m("text-to-video", "Text to video", "bytedance/v1-pro-text-to-video"),
      m("image-to-video", "Image to video", "bytedance/v1-pro-image-to-video"),
    ],
  },
  {
    id: "seedance-1-pro-fast",
    name: "Seedance 1.0 Pro Fast",
    vendor: "ByteDance",
    category: "video",
    output: "video",
    tagline: "Seedance 1.0 Pro at the faster, cheaper tier.",
    modes: [m("image-to-video", "Image to video", "bytedance/v1-pro-fast-image-to-video")],
  },
  {
    id: "seedance-1-lite",
    name: "Seedance 1.0 Lite",
    vendor: "ByteDance",
    category: "video",
    output: "video",
    tagline: "The lightest Seedance 1.0 tier, in text and image modes.",
    modes: [
      m("text-to-video", "Text to video", "bytedance/v1-lite-text-to-video"),
      m("image-to-video", "Image to video", "bytedance/v1-lite-image-to-video"),
    ],
  },
  {
    id: "kling-3",
    featured: true,
    prompts: [
      "Two shots: a lighthouse in a storm, then the keeper lighting a lamp inside",
      "Drone rises over a terraced tea plantation at sunrise, mist in the valleys",
    ],
    name: "Kling 3.0",
    vendor: "Kuaishou",
    category: "video",
    output: "video",
    badge: "MULTI-SHOT",
    tagline: "Multi-shot storytelling with native audio and element references.",
    modes: [
      m("text-to-video", "Text to video", "kling-3.0/video", {
        hide: ["image_urls", "multi_prompt"],
        fixed: { multi_shots: false },
        require: ["prompt"],
      }),
      m("image-to-video", "Image to video", "kling-3.0/video", {
        hint: "First frame, or first + last",
        hide: ["multi_prompt"],
        fixed: { multi_shots: false },
        require: ["image_urls", "prompt"],
      }),
      m("multi-shot", "Multi-shot", "kling-3.0/video", {
        hint: "Up to five shots in one run",
        hide: ["prompt"],
        fixed: { multi_shots: true },
        require: ["multi_prompt"],
      }),
    ],
  },
  {
    id: "kling-3-omni",
    featured: true,
    prompts: [
      "A dancer in red silk moves through an empty marble hall, camera circling",
      "Time-lapse of a city square from dawn to night, crowds flowing like water",
    ],
    name: "Kling 3.0 Omni",
    vendor: "Kuaishou",
    category: "video",
    output: "video",
    badge: "4K",
    tagline: "Kling 3.0's omni model: text, frames, references and video transformation up to 4K.",
    modes: [
      m("text-to-video", "Text to video", "kling-3.0-omni/text-to-video"),
      m("first-frame", "First frame", "kling-3.0-omni/image-to-video", { variant: "Single First Frame" }),
      m("first-last", "First + last frame", "kling-3.0-omni/image-to-video", { variant: "First and Last Frames" }),
      m("ref-images", "Reference · Images", "kling-3.0-omni/reference-to-video", { variant: "No Video Input" }),
      m("ref-video", "Reference · Video", "kling-3.0-omni/reference-to-video", { variant: "Video Input Only" }),
      m("ref-mixed", "Reference · Video + images", "kling-3.0-omni/reference-to-video", { variant: "Video with Images" }),
      m("transform-video", "Transform · Video", "kling-3.0-omni/transformation", { variant: "Video Input Only" }),
      m("transform-mixed", "Transform · Video + images", "kling-3.0-omni/transformation", { variant: "Video with Images" }),
    ],
  },
  {
    id: "kling-v3-turbo",
    name: "Kling V3 Turbo",
    vendor: "Kuaishou",
    category: "video",
    output: "video",
    tagline: "The quick Kling 3 variant at 720p or 1080p.",
    modes: [
      m("text-to-video", "Text to video", "kling/v3-turbo-text-to-video"),
      m("image-to-video", "Image to video", "kling/v3-turbo-image-to-video"),
    ],
  },
  {
    id: "kling-2-6",
    name: "Kling 2.6",
    vendor: "Kuaishou",
    category: "video",
    output: "video",
    badge: "AUDIO",
    tagline: "Kling 2.6 with native sound.",
    modes: [
      m("text-to-video", "Text to video", "kling-2.6/text-to-video"),
      m("image-to-video", "Image to video", "kling-2.6/image-to-video"),
    ],
  },
  {
    id: "kling-2-5-turbo",
    name: "Kling 2.5 Turbo",
    vendor: "Kuaishou",
    category: "video",
    output: "video",
    tagline: "Kling 2.5 Turbo Pro text-to-video.",
    modes: [m("text-to-video", "Text to video", "kling/v2-5-turbo-text-to-video-pro")],
  },
  {
    id: "kling-2-1-standard",
    name: "Kling 2.1 Standard",
    vendor: "Kuaishou",
    category: "video",
    output: "video",
    tagline: "The entry tier of Kling 2.1, from a first frame.",
    modes: [m("image-to-video", "Image to video", "kling/v2-1-standard")],
  },
  {
    id: "kling-2-1-pro",
    name: "Kling 2.1 Pro",
    vendor: "Kuaishou",
    category: "video",
    output: "video",
    tagline: "The Pro tier of Kling 2.1, from a first frame.",
    modes: [m("image-to-video", "Image to video", "kling/v2-1-pro")],
  },
  {
    id: "kling-2-1-master",
    name: "Kling 2.1 Master",
    vendor: "Kuaishou",
    category: "video",
    output: "video",
    tagline: "The top tier of Kling 2.1, in text and image modes.",
    modes: [
      m("text-to-video", "Text to video", "kling/v2-1-master-text-to-video"),
      m("image-to-video", "Image to video", "kling/v2-1-master-image-to-video"),
    ],
  },
  {
    id: "kling-3-motion-control",
    name: "Kling 3.0 Motion Control",
    vendor: "Kuaishou",
    category: "video",
    output: "video",
    tagline: "Drive a character image with the motion of a reference video.",
    modes: [m("generate", "Generate", "kling-3.0/motion-control")],
    fields: MOTION_CONTROL_FIELDS,
  },
  {
    id: "kling-2-6-motion-control",
    name: "Kling 2.6 Motion Control",
    vendor: "Kuaishou",
    category: "video",
    output: "video",
    tagline: "The 2.6 generation of motion transfer from a reference video.",
    modes: [m("generate", "Generate", "kling-2.6/motion-control")],
    fields: MOTION_CONTROL_FIELDS,
  },
  {
    id: "kling-avatar",
    name: "Kling Avatar",
    vendor: "Kuaishou",
    category: "video",
    output: "video",
    tagline: "Talking avatar from a portrait and an audio track, at 720p.",
    modes: [m("generate", "Generate", "kling/ai-avatar-standard")],
  },
  {
    id: "kling-avatar-pro",
    name: "Kling Avatar Pro",
    vendor: "Kuaishou",
    category: "video",
    output: "video",
    tagline: "The 1080p tier of Kling Avatar.",
    modes: [m("generate", "Generate", "kling/ai-avatar-pro")],
  },
  {
    id: "minimax-h3",
    featured: true,
    prompts: [
      "A paper boat drifts down a rain-filled gutter, reflections of shop signs",
      "Macro of ink dropping into water, blooming into a jellyfish shape",
    ],
    name: "Hailuo 03 (H3)",
    vendor: "MiniMax",
    category: "video",
    output: "video",
    tagline: "MiniMax H3: text, frame-guided and multimodal reference video up to 2K.",
    modes: [
      m("text-to-video", "Text to video", "minimax-h3/text-to-video"),
      m("image-to-video", "Image to video", "minimax-h3/image-to-video", { require: ["first_frame_url"] }),
      m("reference-to-video", "Reference", "minimax-h3/reference-to-video"),
    ],
  },
  {
    id: "hailuo-2-3",
    name: "Hailuo 2.3",
    vendor: "MiniMax",
    category: "video",
    output: "video",
    tagline: "Hailuo 2.3 from a first frame, at the standard tier.",
    modes: [m("image-to-video", "Image to video", "hailuo/2-3-image-to-video-standard")],
  },
  {
    id: "hailuo-2-3-pro",
    name: "Hailuo 2.3 Pro",
    vendor: "MiniMax",
    category: "video",
    output: "video",
    tagline: "The Pro tier of Hailuo 2.3.",
    modes: [m("image-to-video", "Image to video", "hailuo/2-3-image-to-video-pro")],
  },
  {
    id: "hailuo-02",
    name: "Hailuo 02",
    vendor: "MiniMax",
    category: "video",
    output: "video",
    tagline: "Hailuo 02 in text and image modes, at the standard tier.",
    modes: [
      m("text-to-video", "Text to video", "hailuo/02-text-to-video-standard"),
      m("image-to-video", "Image to video", "hailuo/02-image-to-video-standard"),
    ],
  },
  {
    id: "hailuo-02-pro",
    name: "Hailuo 02 Pro",
    vendor: "MiniMax",
    category: "video",
    output: "video",
    tagline: "The Pro tier of Hailuo 02, in text and image modes.",
    modes: [
      m("text-to-video", "Text to video", "hailuo/02-text-to-video-pro"),
      m("image-to-video", "Image to video", "hailuo/02-image-to-video-pro"),
    ],
  },
  {
    id: "wan-3",
    featured: true,
    prompts: [
      "A tram crosses a snowy bridge at blue hour, headlights cutting the fog",
      "A potter's hands shape a bowl on a wheel, warm studio light",
    ],
    name: "Wan 3.0",
    vendor: "Alibaba",
    category: "video",
    output: "video",
    badge: "NEW",
    tagline: "All-purpose references: images, video, audio, even a document or a link.",
    modes: [m("video", "Video", "wan/3-0-video")],
  },
  {
    id: "wan-3-prime",
    name: "Wan 3.0 Prime",
    vendor: "Alibaba",
    category: "video",
    output: "video",
    badge: "NEW",
    tagline: "The highest-quality Wan 3.0 tier, with the same references.",
    modes: [m("video", "Video", "wan/3-0-video-prime")],
  },
  {
    id: "wan-2-7",
    name: "Wan 2.7",
    vendor: "Alibaba",
    category: "video",
    output: "video",
    tagline: "Four modes in one model, including audio-driven faces and video editing.",
    modes: [
      m("text-to-video", "Text to video", "wan/2-7-text-to-video"),
      m("image-to-video", "Image to video", "wan/2-7-image-to-video"),
      m("reference-to-video", "Reference", "wan/2-7-r2v"),
      m("video-edit", "Video edit", "wan/2-7-videoedit"),
    ],
  },
  {
    id: "wan-2-6",
    name: "Wan 2.6",
    vendor: "Alibaba",
    category: "video",
    output: "video",
    tagline: "Wan 2.6 in text, image and video-to-video modes.",
    modes: [
      m("text-to-video", "Text to video", "wan/2-6-text-to-video"),
      m("image-to-video", "Image to video", "wan/2-6-image-to-video"),
      m("video-to-video", "Video to video", "wan/2-6-video-to-video"),
    ],
  },
  {
    id: "wan-2-6-flash",
    name: "Wan 2.6 Flash",
    vendor: "Alibaba",
    category: "video",
    output: "video",
    tagline: "The quicker Wan 2.6 tier, from an image or a video.",
    modes: [
      m("image-to-video", "Image to video", "wan/2-6-flash-image-to-video"),
      m("video-to-video", "Video to video", "wan/2-6-flash-video-to-video"),
    ],
  },
  {
    id: "wan-2-5",
    name: "Wan 2.5",
    vendor: "Alibaba",
    category: "video",
    output: "video",
    tagline: "Wan 2.5 text and image to video.",
    modes: [
      m("text-to-video", "Text to video", "wan/2-5-text-to-video"),
      m("image-to-video", "Image to video", "wan/2-5-image-to-video"),
    ],
  },
  {
    id: "wan-2-2",
    name: "Wan 2.2 Turbo",
    vendor: "Alibaba",
    category: "video",
    output: "video",
    tagline: "Wan 2.2 A14B Turbo: text, image and speech-driven video.",
    modes: [
      m("text-to-video", "Text to video", "wan/2-2-a14b-text-to-video-turbo"),
      m("image-to-video", "Image to video", "wan/2-2-a14b-image-to-video-turbo"),
      m("speech-to-video", "Speech to video", "wan/2-2-a14b-speech-to-video-turbo"),
    ],
  },
  {
    id: "wan-animate",
    name: "Wan Animate",
    vendor: "Alibaba",
    category: "video",
    output: "video",
    tagline: "Transfer motion onto a character, or swap the character in a clip.",
    modes: [
      m("move", "Animate", "wan/2-2-animate-move", { hint: "Motion moves onto your image" }),
      m("replace", "Replace", "wan/2-2-animate-replace", { hint: "Your character replaces the one in the video" }),
    ],
  },
  {
    id: "happyhorse-1-1",
    name: "HappyHorse 1.1",
    vendor: "Alibaba",
    category: "video",
    output: "video",
    badge: "NEW",
    tagline: "HappyHorse 1.1 with nine aspect ratios.",
    modes: [
      m("text-to-video", "Text to video", "happyhorse-1-1/text-to-video"),
      m("image-to-video", "Image to video", "happyhorse-1-1/image-to-video"),
      m("reference-to-video", "Reference", "happyhorse-1-1/reference-to-video"),
    ],
  },
  {
    id: "happyhorse-1",
    name: "HappyHorse 1.0",
    vendor: "Alibaba",
    category: "video",
    output: "video",
    tagline: "Long-form generation and video editing with up to nine references.",
    modes: [
      m("text-to-video", "Text to video", "happyhorse/text-to-video"),
      m("image-to-video", "Image to video", "happyhorse/image-to-video"),
      m("reference-to-video", "Reference", "happyhorse/reference-to-video"),
      m("video-edit", "Video edit", "happyhorse/video-edit"),
    ],
  },
  {
    id: "pixverse-v6",
    featured: true,
    prompts: [
      "A skateboarder lands a trick in an empty parking garage, neon light, slow motion",
    ],
    name: "PixVerse V6",
    vendor: "PixVerse",
    category: "video",
    output: "video",
    badge: "NEW",
    tagline: "Effect templates, fusion references, transitions and extension.",
    modes: [
      m("text-to-video", "Text to video", "pixverse-v6/text-to-video"),
      m("image-to-video", "Image to video", "pixverse-v6/image-to-video"),
      m("transition", "Transition", "pixverse-v6/transition", { hint: "First and last frame" }),
      m("reference-to-video", "Fusion", "pixverse-v6/reference-to-video", { hint: "Named subject and background references" }),
      m("extend-task", "Extend", "pixverse-v6/extend", { variant: "TaskId", hint: "From a previous PixVerse task" }),
      m("extend-video", "Extend (video)", "pixverse-v6/extend", { variant: "Video", hint: "From an uploaded clip" }),
    ],
  },
  {
    id: "grok-imagine-video",
    name: "Grok Imagine Video",
    vendor: "xAI",
    category: "video",
    output: "video",
    tagline: "Fast video with fun / normal / spicy styles, plus upscale and extend.",
    modes: [
      m("text-to-video", "Text to video", "grok-imagine/text-to-video"),
      m("image-to-video", "Image to video", "grok-imagine/image-to-video"),
      m("upscale", "Upscale", "grok-imagine/upscale"),
      m("extend", "Extend", "grok-imagine/extend"),
    ],
    fields: {
      extend_times: {
        kind: "segmented",
        placement: "bar",
        choices: [
          { value: "6", label: "6s" },
          { value: "10", label: "10s" },
        ],
      },
    },
  },
  {
    id: "grok-imagine-video-1-5",
    name: "Grok Imagine Video 1.5",
    vendor: "xAI",
    category: "video",
    output: "video",
    badge: "PREVIEW",
    tagline: "The 1.5 preview: up to seven references at 1080p.",
    modes: [m("generate", "Generate", "grok-imagine-video-1-5-preview")],
  },
  {
    id: "gemini-omni",
    name: "Gemini Omni",
    vendor: "Google",
    category: "video",
    output: "video",
    badge: "4K",
    tagline: "Reusable characters and voices across videos, up to 4K.",
    validate: omniBudget,
    modes: [
      m("video", "Video", "gemini-omni-video"),
      m("character", "Create character", "gemini-omni-character", { hint: "Reusable identity" }),
      m("audio", "Create voice", "gemini-omni-audio", { hint: "Reusable voice" }),
    ],
  },
  {
    id: "gemini-omni-flash-1-1",
    name: "Gemini Omni 1.1 Flash",
    vendor: "Google",
    category: "video",
    output: "video",
    tagline: "The Flash generation of Omni video, with the same characters and voices.",
    validate: omniBudget,
    // A first frame rules out every reference input, so the two ways in are
    // modes of their own rather than one bar that sends a clash.
    modes: [
      m("video", "Reference", "google/gemini-omni-flash-1-1", {
        hint: "Images, a video, characters and voices",
        hide: ["first_frame_url", "last_frame_url"],
      }),
      m("frames", "Frames", "google/gemini-omni-flash-1-1", {
        hint: "First frame, optionally a last frame",
        hide: ["image_urls", "video_list", "audio_ids", "character_ids"],
        require: ["first_frame_url"],
      }),
    ],
  },
  {
    id: "runway",
    featured: true,
    prompts: [
      "A vintage convertible drives along a coastal cliff road, cinematic wide shot",
    ],
    name: "Runway",
    vendor: "Runway",
    category: "video",
    output: "video",
    tagline: "Runway generation, extension and Aleph video-to-video.",
    modes: [
      m("generate", "Generate", "runway", { hint: "Text, or image to video" }),
      m("extend", "Extend", "runway/extend-ai-video"),
    ],
    fields: RUNWAY_FIELDS,
  },
  {
    id: "runway-gen4-aleph",
    name: "Runway Gen-4 Aleph",
    vendor: "Runway",
    category: "video",
    output: "video",
    tagline: "Prompt-driven transformation of a video you already have.",
    modes: [m("generate", "Generate", "runway/gen4-aleph")],
    fields: RUNWAY_FIELDS,
  },

  /* ============================================================== *
   * AUDIO
   * ============================================================== */
  {
    id: "suno-music",
    featured: true,
    prompts: [
      "Dreamy synth-pop about driving home at 3am, female vocal, slow build",
      "Instrumental lo-fi hip hop for a rainy study session, vinyl crackle",
    ],
    name: "Suno",
    vendor: "Suno",
    category: "audio",
    output: "audio",
    badge: "V6",
    tagline: "Full songs from a brief or your own lyrics: extend, cover, mash up and more.",
    modes: [
      m("generate", "Generate", "ai-music-api/generate"),
      m("extend", "Extend", "ai-music-api/extend", { hint: "Continue a generated track" }),
      m("cover-audio", "Cover audio", "ai-music-api/upload-and-cover-audio", { hint: "Re-imagine an uploaded track" }),
      m("extend-audio", "Extend audio", "ai-music-api/upload-and-extend-audio", { hint: "Continue an uploaded track" }),
      m("add-vocals", "Add vocals", "ai-music-api/add-vocals"),
      m("add-instrumental", "Add instrumental", "ai-music-api/add-instrumental"),
      m("mashup", "Mashup", "ai-music-api/mashup", { hint: "Blend two uploads" }),
      m("replace-section", "Replace section", "ai-music-api/replace-section", {
        variant: "Replace section using existing audio",
      }),
      m("replace-section-upload", "Replace section (upload)", "ai-music-api/replace-section", {
        variant: "Replace section using uploaded custom audio",
      }),
      m("sounds", "Sounds", "ai-music-api/sounds", { hint: "Short sound design clips" }),
    ],
    fields: {
      prompt: { label: "Prompt / lyrics", placeholder: "Describe the song, or paste lyrics in Custom mode…" },
    },
  },
  {
    id: "suno-studio",
    name: "Suno Studio",
    vendor: "Suno",
    category: "audio",
    output: "audio",
    tagline: "Everything around a track: lyrics, stems, MIDI, WAV, cover art and video.",
    modes: [
      m("lyrics", "Lyrics", "ai-music-api/generate-lyrics"),
      m("timestamped-lyrics", "Timestamped lyrics", "ai-music-api/timeStamped-lyrics"),
      m("boost-style", "Boost style", "ai-music-api/boost-music-style", { hint: "Expand a style brief" }),
      m("stems", "Stems", "ai-music-api/separate-vocals", { variant: "Separate using existing audio" }),
      m("stems-upload", "Stems (upload)", "ai-music-api/separate-vocals", {
        variant: "Separate using user-uploaded audio",
      }),
      m("midi", "MIDI", "ai-music-api/generate-midi-from-audio"),
      m("wav", "Convert to WAV", "ai-music-api/convert-to-wav-format"),
      m("cover-art", "Cover art", "ai-music-api/cover-generate"),
      m("music-video", "Music video", "ai-music-api/create-music-video"),
      m("persona", "Persona", "ai-music-api/generate-persona"),
      m("recover", "Recover audio", "ai-music-api/suno-recovery-audio"),
    ],
  },
  {
    id: "suno-voice",
    name: "Suno Voice",
    vendor: "Suno",
    category: "audio",
    output: "audio",
    tagline: "Clone a custom voice for Suno from a verified sample.",
    modes: [
      m("validate", "Verification phrase", "ai-music-api/validation-phrase"),
      m("regenerate", "Regenerate phrase", "ai-music-api/regenerate-phrase"),
      m("create", "Create voice", "ai-music-api/create-voice"),
      m("check", "Check availability", "ai-music-api/check-voice"),
    ],
  },
  {
    id: "elevenlabs-speech",
    featured: true,
    prompts: [
      "Welcome aboard. Please stow your bags and take your seat \u2014 we'll be leaving shortly.",
      "Chapter one. The lighthouse had been dark for eleven years.",
    ],
    name: "ElevenLabs Turbo 2.5",
    vendor: "ElevenLabs",
    category: "audio",
    output: "audio",
    tagline: "The fastest ElevenLabs speech model, in 67 stock voices.",
    modes: [m("speak", "Speak", "elevenlabs/text-to-speech-turbo-2-5")],
    fields: { text: { label: "Script", placeholder: "Type what the voice should say…" } },
  },
  {
    id: "elevenlabs-multilingual-v2",
    name: "ElevenLabs Multilingual v2",
    vendor: "ElevenLabs",
    category: "audio",
    output: "audio",
    tagline: "The steadiest ElevenLabs model across languages, same voices.",
    modes: [m("speak", "Speak", "elevenlabs/text-to-speech-multilingual-v2")],
    fields: { text: { label: "Script", placeholder: "Type what the voice should say…" } },
  },
  {
    id: "elevenlabs-dialogue",
    name: "ElevenLabs Dialogue",
    vendor: "ElevenLabs",
    category: "audio",
    output: "audio",
    badge: "V3",
    tagline: "Multi-voice dialogue from a script of lines and voices.",
    modes: [m("dialogue", "Dialogue", "elevenlabs/text-to-dialogue-v3")],
  },
  {
    id: "gemini-tts",
    name: "Gemini 3.1 Flash TTS",
    vendor: "Google",
    category: "audio",
    output: "audio",
    tagline: "Multi-speaker speech with named voices, accents and delivery styles.",
    modes: [m("speak", "Speak", "google/gemini-3-1-flash-tts")],
  },
  {
    id: "gemini-tts-pro",
    name: "Gemini 2.5 Pro TTS",
    vendor: "Google",
    category: "audio",
    output: "audio",
    tagline: "The Pro generation of Gemini speech, same voices and styles.",
    modes: [m("speak", "Speak", "google/gemini-2-5-pro-tts")],
  },

  /* ============================================================== *
   * TOOLS
   * ============================================================== */
  {
    id: "topaz",
    name: "Topaz Upscale",
    vendor: "Topaz Labs",
    category: "tool",
    output: "image",
    tagline: "Enhance and upscale images or video up to 4×.",
    modes: [
      m("image", "Image", "topaz/image-upscale"),
      m("video", "Video", "topaz/video-upscale"),
    ],
  },
  {
    id: "recraft",
    name: "Recraft Tools",
    vendor: "Recraft",
    category: "tool",
    output: "image",
    tagline: "Background removal and crisp upscaling.",
    modes: [
      m("remove-background", "Remove background", "recraft/remove-background"),
      m("crisp-upscale", "Crisp upscale", "recraft/crisp-upscale"),
    ],
  },
  {
    id: "elevenlabs-isolation",
    name: "Audio Isolation",
    vendor: "ElevenLabs",
    category: "tool",
    output: "audio",
    tagline: "Strip background noise and keep the voice.",
    modes: [m("isolate", "Isolate", "elevenlabs/audio-isolation")],
  },
];
